# Generated by Django 3.1.7 on 2021-06-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210604_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherlocation',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherlocation',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherlocation',
            name='icon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherlocation',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
